### ISSUE TITLE
Is it possible to upgrade to Monterey?

### ISSUE THREAD

**Issue by Buns0705** [vivzero/LG-14Z90N-hackintosh#1]
Hi, I also have an LG 14Z90N and after almost half a year trying to install Opencore in vain I finally succeeded after finding your repo. Thanks from the bottom of my heart!

If possible, I would love to know if there is any chance for Monterey with this EFI?  I need to install Xcode for my self-study, only successfully installed Big Sur a few days ago and am still trying not to mess things up.  Looking forward to your reply.

**Comment by vivzero** [comment]
Yes. I'm using Monterey and it works very well

**Comment by Buns0705** [comment]
Thanks for your confirmation! Btw is there any chance for fixing the problem with the HDMI port?

**Comment by vivzero** [comment]
Afaik, HDMI is Apple's driver problem so unlikely to be fixed...
